### ISSUE TITLE
Add overload to GeoHash.encode to include both length and max parameters

### ISSUE THREAD

**Issue by davidmoten** [davidmoten/geo#17]
As requested by @abrin.

David,
  As I use it a bit, it might be nice to expose both "length" and “max” to the encode functions. Right now, one has to make the choice between either having a number of hashes or a max length of a hash. But, if you’re selecting a larger region it likely becomes important to have access to both.

thanks,

adam

**Comment by davidmoten** [comment]
Can you give a bit more detail @abrin. What function(s) would you like to change?

**Comment by abrin** [comment]
For what I was looking at it would be GeoHash.coverBoundingBox. The only way to get a high level of detail for a large bounding area would be to break it into smaller subsections. What would be useful would be GeoHash.coverBoundingBox(minLat, minLon, maxLat, maxLon, hashLength, maxHashes).  Then, one could specify a hash at say a length of 6, but also request but to 2048 of them or however many.    Does this make sense? if not, Ive found a way around it.

- adam

**Comment by davidmoten** [comment]
I don't yet understand because you can get as high a level of detail as you
want by passing a larger hash length. The number of hashes is then derived
from that length.

On 11 Mar 2015 14:34, "abrin" <notifications@github.com> wrote:
>
> For what I was looking at it would be GeoHash.coverBoundingBox. The only
way to get a high level of detail for a large bounding area would be to
break it into smaller subsections. What would be useful would be
GeoHash.coverBoundingBox(minLat, minLon, maxLat, maxLon, hashLength,
maxHashes). Then, one could specify a hash at say a length of 6, but also
request but to 2048 of them or however many. Does this make sense? if not,
Ive found a way around it.
>
> - adam
>
> > On Mar 10, 2015, at 8:13 PM, Dave Moten <notifications@github.com>
wrote:
> >
> > Can you give a bit more detail @abrin. What function(s) would you like
to change?

**Comment by abrin** [comment]
David,
  That is correct. Reading the code, reading through the code, I think I had a misunderstanding from the javadoc that the coverBoundingBox method which specifies length was limited to the MAX_BOUNDING (12) hashes, but it appears to not be. Go ahead and close this issue and i'll submit a patch request if I hit an issue that needs adjustment.
