### ISSUE TITLE
Consider removing synchronized on GeoHash::heightDegrees

### ISSUE THREAD

**Issue by Crystark** [davidmoten/geo#19]
Hi !

We're using the `GeoHash.hashContains` with 2 to 4-char geohashes and are seeing that the static method `heightDegrees` comes up as a Hot spot during our CPU sampling with VisualVM. I noticed this method is synchronized so I was wondering if it may be a good idea to pre-calculate all `MAX_HASH_LENGTH` (12) values in a static way so you can remove the synchronization ?

Is this something you may consider changing ?

Thanks
Regards

**Comment by davidmoten** [comment]
You bet, we can fix that. I've used a static holder pattern for on-demand instantiation of the widths and heights and removed the use of `sychronized` from `heightDegrees` and `widthDegrees`. I'll release very shortly.

**Comment by davidmoten** [comment]
The fix has been released to Maven Central version 0.7.4. Let me know where your next hot spot is!

**Comment by davidmoten** [comment]
**Benchmarks**
Before and after = 30% improvement in throughput. I imagine the result is not bigger because this test is run synchronously and the repeated calls to the synchronous method would be subject to biased locking and thus not as expensive as when part of a program with asynchrony. 
```
Benchmarks.hashContains  thrpt   10   9461061.308 ± 137065.485  ops/s
Benchmarks.hashContains  thrpt   10  12182455.956 ± 259831.091  ops/s
```

**Comment by Crystark** [comment]
Thanks! Works like a charm.
