### ISSUE TITLE
GeoHash#encodeHash(double, double, int) allows invalid 'length'

### ISSUE THREAD

**Issue by ShibaBandit** [davidmoten/geo#29]
Nested call to GeoHash#fromLongToString(long) does a range check on a hash, but only catches some invalid cases. I can pass in 20 for the length in encodeHash() for example and I wind up with a shorter hash instead of an error. Passing in 13 for the length throws an error.

**Comment by davidmoten** [comment]
Editing title because is the (double, double, int) signature

**Comment by davidmoten** [comment]
Thanks for the report @ShibaBandit! Fix has been applied and new release is on Maven Central now (0.7.6).
